### ISSUE TITLE
Does not work with RAID

### ISSUE THREAD

**Issue by Joeviocoe** [the2nd/ykluks#3]
Qubes 4 set up does allow for an encrypted raid the graphical setup.  It does not create an lvm.  I am using a separate drive with luks and an lvm thin pool.

So now I have 3 luks partitions opened on boot.  / (root), swap, and secondary drive that isn't important to the OS.

The way grub is set up by default now, is to have multiple "rd.luks.uuid=" parameters, one for each.  Also, after each luks parameter, if one of the raid volumes, there is a "rd.md.uuid=" parameter.
This works using a single luks passphrase at boot time.

Original GRUB command line: 
`placeholder root=UUID=<root_uuid> ro rd.luks.uuid=luks-<UUID1> rd.luks.uuid=luks-<UUID2>  rd.luks.uuid=luks-<UUID3>  rd.md.uuid=<RAID_UUID1>  rd.md.uuid=<RAID_UUID2> i915.alpha_support=1 rhgb quiet rd.qubes.hide_all_usb`

So now I am thinking about your setup instructions, in this scenario.

From what I've tested, multiple "rd.ykluks.uuid" and entries on the grub line, tries to invoke multiple instances, and boot fails.  I then tried a single rd.ykluks.uuid parameter with the comma separated uuids. And keep the existing "rd.md.uuid" parameters after that.

It doesn't work.  I just get a blinking cursor, no prompts or messages.
I've tried removing the "luks-" prefix on the UUIDs, but still fails.

If I remove the "rd.md.uuid" parameters... I do get prompted for yubikey password and it does begin to decrypt the volumes as expected.  But without the raid mounting "md" parameters... it doesn't boot from there.

**Comment by the2nd** [comment]
I do not have a Qubes 4 installation to test nor do i have ever setup an encrypted RAID with Qubes/fedora/dracut. So i am not sure how to fix this problem.

What i've done is to update the ykluks.sh to use getargs instead of getarg which should allow you to specify the LUKS UUIDs with multiple rd.ykluks.uuid=UUID.

I've also added the same depends() in module-setup.sh as the normal crypt module. But i am unsure if this does have any effect. Maybe you can have a look at the 90crypt module in /usr/lib/dracut/modules.d of your Qubes 4 installation and get an idea whats missing to get it working with the software raid. On my qubes installation the is also a 90mdraid module, so you might check this too.

**Comment by Joeviocoe** [comment]
Great.  The new changes seem to work.

For posterity, this is the LUKS over RAID  configuration that I was able to create using the Qubes 4 installation wizard, and an added LVM over LUKS done after install:
```
NAME                                                     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1                                                  259:0    0 232.9G  0 disk  
├─nvme0n1p3                                              259:4    0    10G  0 part  
│ └─md126                                                  9:126  0    20G  0 raid0 
│   └─luks-<UUID2>                                           253:1    0    20G  0 crypt [SWAP]
├─nvme0n1p1                                              259:1    0   248M  0 part  /boot
└─nvme0n1p2                                              259:2    0 222.6G  0 part  
  └─md127                                                  9:127  0   445G  0 raid0 
    └─luks-<UUID1>                                            253:0    0   445G  0 crypt /
nvme1n1                                                  259:3    0 232.9G  0 disk  
├─nvme1n1p2                                              259:6    0    10G  0 part  
│ └─md126                                                  9:126  0    20G  0 raid0 
│   └─luks-<UUID2>                                          253:1    0    20G  0 crypt [SWAP]
└─nvme1n1p1                                              259:5    0 222.6G  0 part  
  └─md127                                                  9:127  0   445G  0 raid0 
    └─luks-<UUID1>                                            253:0    0   445G  0 crypt /
sda                                                        8:0    0   5.5T  0 disk  
└─luks-<UUID3>                                                253:2    0   5.5T  0 crypt 
  ├─qubes-pool01_tdata                                    253:4    0   5.5T  0 lvm   
  │ └─qubes-pool01-tpool                                  253:5    0   5.5T  0 lvm   
  │   ├─qubes-pool01                                         253:6    0   5.5T  0 lvm   
  └─qubes-pool01_tmeta                                   253:3    0    88M  0 lvm   
    └─qubes-pool01-tpool                                   253:5    0   5.5T  0 lvm   
      ├─qubes-pool01                                          253:6    0   5.5T  0 lvm 
```

--------------

My /usr/lib/dracut/modules.d/90crypt/module-setup.sh does show these dependencies:
So I added the "**dm**" too.

```
depends() {
    echo dm rootfs-block
    return 0
}
```

On the first and second boot, it seemed to hang with a black screen, single blinking cursor,... but booted into "init=/usr/bin/bash" for single user mode... which did work so I just rebooted.  So far, subsequent boots do work.

Thanks.
