### ISSUE TITLE
Re: Qubes OS 4.1 compatibility

### ISSUE THREAD

**Issue by Joeviocoe** [the2nd/ykluks#5]
Does this work with Qubes OS 4.1?

**Comment by the2nd** [comment]
Yes this works with my 4.1 installation.

**Comment by Joeviocoe** [comment]
Thanks for confirming.

A few updates to the README might be needed.

1. `sudo cryptsetup LuksDump /dev/sdXX` -> `sudo cryptsetup luksDump /dev/sdXX`  _lowercase luks_
2. `sudo grub2-mkconfig > /boot/grub2/grub.cfg` should note for legacy bios.  Run `grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg` for UEFI
3. _Please note that the current version is tested with a LVM-on-LUKS setup only. The default Qubes OS installation is a LUKS-on-LVM setup which will not work yet._   
I don't think that's been the default since Qubes 3.2 so this warning isn't needed.  The default for Qubes 4 (LVM-on-LUKS) has been working with ykluks.
4. _Comment out all lines in crypttab._ ->  Comment out all lines in /etc/crypttab
5. _Change the line with "rd.qubes.hide_all_usb" in /etc/default/grub to "rd.ykluks.hide_all_usb"_ should also include instructions for those with a fresh 4.1 installation or adding a USB qube after. 

"rd.qubes.hide_all_usb" is deprecated, Qubes is now using [USBGuard configuration](https://www.qubes-os.org/doc/usb-qubes/#qubes-41-how-to-enable-a-usb-keyboard-on-a-separate-usb-controller) with "usbcore.authorized_default=0".  
**Change "usbcore.authorized_default=0" to "usbcore.authorized_default=-1"** in the [kernel parameters](https://www.kernel.org/doc/html/v5.0/admin-guide/kernel-parameters.html)

ykluks.sh:125  `# Make sure we hide devices from dom0 after yubikey/luks setup.`
I'm not sure if the dracut code needs to be modified to de-authorize USB devices after luks is decrypted, in a similar way to the current hide_devices() function.  It seems that the code looks for ykluks.hide_all_usb.
ykluks.sh:42 `if getargbool 0 rd.ykluks.hide_all_usb; then`
